name: Run Playwright Tests on Electron



on:
  workflow_dispatch:
    inputs:
        version:
          description: 'version'
          required: true

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Playwright
      uses: actions/checkout@v4
      with:
        repository: microsoft/playwright
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install Dependencies
      run: npm ci
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - name: Handle electron-to-chromium Bug
      run: |
        curl -O -L https://github.com/microsoft/playwright/pull/28826.patch
        git apply 28826.patch
    - name: Update Electron to ${{ github.event.inputs.version }}
      run: npm i electron@${{ github.event.inputs.version }}
    - name: Build Playwright
      run: npm run build
    - name: Install Chromium
      run: npx playwright install --with-deps chromium
    - name: Run Tests (Linux)
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run etest
      if: matrix.os == 'ubuntu-latest'
    - name: Run Tests (Non-Linux)
      run: npm run etest
      if: matrix.os != 'ubuntu-latest'
  